access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyVVVJRCI6Ijg5NmViN2YzLTFjNmEtNGViNy04NDM3LTQxOTBkZjZhYmFjNiIsImlzcyI6ImJvb3QuZGV2IiwiZXhwIjoxNzc4NjUxNzA0LCJpYXQiOjE3Nzg2NDgxMDR9.VC7fj10-mZSut7WziSBbXSbJhS854yYTg8Thsb3KM04
api_url: https://api.boot.dev
color:
    gray: "8"
    green: "2"
    magenta: "5"
    red: "1"
frontend_url: https://boot.dev
last_refresh: 1778648104
refresh_token: VMUgHBYcBzBrBhJXgqazbFIv7lTcQZRS
